### ISSUE TITLE
Enabling `show-actuator` doesn't work with Spring-Boot 2.3.8.RELEASE

### ISSUE THREAD

**Issue by oliverlockwood** [springdoc/springdoc-openapi#1063]
**Describe the bug**
```
java.lang.NoSuchMethodError: org.springframework.boot.actuate.autoconfigure.web.server.ManagementServerProperties.getBasePath()Ljava/lang/String;
	at org.springdoc.core.ActuatorProvider.getActuatorPath(ActuatorProvider.java:176)
	at org.springdoc.api.AbstractOpenApiResource.getActuatorURI(AbstractOpenApiResource.java:1062)
	at org.springdoc.webmvc.api.OpenApiActuatorResource.getServerUrl(OpenApiActuatorResource.java:152)
	at org.springdoc.webmvc.api.OpenApiResource.calculateServerUrl(OpenApiResource.java:325)
	at org.springdoc.webmvc.api.OpenApiResource.openapiJson(OpenApiResource.java:175)
	at org.springdoc.webmvc.api.MultipleOpenApiWebMvcResource.openapiJson(MultipleOpenApiWebMvcResource.java:93)
        ...
```

**To Reproduce**
- Using spring-boot `2.3.8.RELEASE`
- Using `springdoc-openapi-ui` version `1.5.4`
- Configuration `springdoc.show-actuator: true`

**Expected behavior**
- actuator endpoints are accessible in the Swagger UI

**Actual behaviour**
- actuator endpoints are **not** accessible in the Swagger UI, and stacktraces such as the above are shown.

Inspecting the class, there is clearly no `getBasePath()` method on the `ManagementServierProperties` class in `spring-boot-actuator-autoconfigure-2.3.8.RELEASE`.  Is this a known incompatibility (I know SB that 2.4.x is available; we have yet to upgrade for other reasons) - or does this project need updating?

**Comment by bnasslahsen** [comment]
@oliverlockwood, 

 I am not aware of your context.
 Since, v1.5.0, springdoc-openapi depends on spring-boot 2.4.x and superior.
 You coud use v1.4.8, which doesn't depend on 2.4.x.

 Note that you have access to the source code and you can have the [pom](https://github.com/springdoc/springdoc-openapi/blob/v1.4.8/pom.xml) dependencies, for each version.

**Comment by oliverlockwood** [comment]
Thanks @bnasslahsen for the pointer. You're quite right, I should have stopped to look at the parent POM.  Appreciate your time.
