### ISSUE TITLE
Since 2.0.3 Failed to instantiate [org.springdoc.core.configuration.SpringDocKotlinConfiguration]: Constructor threw exception

### ISSUE THREAD

**Issue by wleese** [springdoc/springdoc-openapi#2134]
**Describe the bug**

After upgrading from 2.0.2 to 2.0.3 our applications (we assume) incorrectly include kotlin autoconfiguration such as `SpringDocKotlinConfiguration.class`, even though our application does not use kotlin directly, but does use `org.springframework.cloud:spring-cloud-starter-kubernetes-fabric8-config:3.0.1` that transitively pulls in some kotlin classes. 

As such, this error is emitted during startup:

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springdoc.core.configuration.SpringDocKotlinConfiguration]: Constructor threw exception
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:223) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:110) ~[spring-beans-6.0.6.jar:6.0.6]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:321) ~[spring-beans-6.0.6.jar:6.0.6]
	... 19 common frames omitted
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/module/kotlin/KotlinModule$Builder
	at org.springdoc.core.configuration.SpringDocKotlinConfiguration.<init>(SpringDocKotlinConfiguration.kt:47) ~[springdoc-openapi-starter-common-2.0.3.jar:2.0.3]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[na:na]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:210) ~[spring-beans-6.0.6.jar:6.0.6]
	... 21 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.module.kotlin.KotlinModule$Builder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	... 28 common frames omitted

```

**To Reproduce**

- What version of spring-boot you are using?
3.0.4

- What modules and versions of springdoc-openapi are you using?

2.0.3

- Provide with a sample code (HelloController) or Test that reproduces the problem

The error can be reproduced with a newly created application using https://start.spring.io/, language Java, Maven, add dependency `Spring Reactive Web`.

Add `springdoc` & `spring-cloud-starter-kubernetes-fabric8-config`:

```
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webflux-api</artifactId>
            <version>2.0.3</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-kubernetes-fabric8-config</artifactId>
            <version>3.0.1</version>
        </dependency>
```

Then just start the application.

**Expected behavior**

- A clear and concise description of what you expected to happen.

No errors, just a running Spring Boot application.

To be clear, we don't use kotlin directly in this application, so there's no need for us to include the missing classes dependency `jackson-module-kotlin`.

**Comment by bnasslahsen** [comment]
@wleese,

Please do not create duplicates

See https://github.com/springdoc/springdoc-openapi/issues/2114

**Comment by wleese** [comment]
@bnasslahsen Ah I missed that issue.

However, I don't believe I should be adding a direct dependency on `jackson-module-kotlin`, because my application does not use kotlin.

Basically, my application is completely unaware of the fact that a dependency on `springdoc-openapi-starter-webflux-api`, will trigger the `jackson-module-kotlin` requirement, just because I'm using `spring-cloud-starter-kubernetes-fabric8-config`.

I believe that a solution here would be to do a `@ConditionalOnClass(com.fasterxml.jackson.module.kotlin.KotlinModule.class)` and not `@ConditionalOnClass(Continuation::class)`. By doing this, this autoconfiguration will only be triggered when the `jackson-module-kotlin` dependency is present, preventing any ClassNotFound issues.

**Comment by breun** [comment]
`springdoc-openapi-starter-common` defines an optional dependency on `jackson-module-kotlin`, but `SpringDocKotlinConfiguration` doesn't check for the presence of `com.fasterxml.jackson.module.kotlin.KotlinModule` before using it, which causes this error.

If `SpringDocKotlinConfiguration` would be annotated with `@ConditionalOnClass(KotlinModule.Builder.class)`, then it could use `jackson-module-kotlin` when it's present on the classpath. Or if `Kotlin.Builder` is considered required for `SpringDocKotlinConfiguration`, then `springdoc-openapi-starter-common` should define a regular dependency on `jackson-module-kotlin` instead of an optional one.

**Comment by bnasslahsen** [comment]
@breun,

`SpringDocKotlinConfiguration` is annotated for checking Kotlin classes presence. 
The project is that now in the v2 with the common module - we can not predict the intention of the project.(whether or not they want enable kotlin support)

Most of the `comments/ issues` i have been reading are related to project dependencies misconfiguration, or people not reading the documentation for v2 and sometimes people not even knowing they were shipping kotlin classes.

We can consider this change: adding an extra `@ConditionalOnClass(KotlinModule.Builder.class)` but there will be a trade-off to accept here:
- Even if the projects doesn't declare `jackson-module-kotlin`, the application will start.  And there will be no notification for people who misconfigure the `kotlin module`, leading sometimes to wrong beans loaded and some other times to wrong results.

If there are more votes for this trade-off, we can definitely consider it.

**Comment by bnasslahsen** [comment]
> @bnasslahsen Ah I missed that issue.
> 
> However, I don't believe I should be adding a direct dependency on `jackson-module-kotlin` as suggested in #2114, because my application does not use kotlin.
> 
> Basically, my application is completely unaware of the fact that a dependency on `springdoc-openapi-starter-webflux-api`, will trigger the `jackson-module-kotlin` requirement, just because I'm using `spring-cloud-starter-kubernetes-fabric8-config` (which just like #2114, is pulled in via `okhttp`).
> 
> I believe that a solution here would be to do a `@ConditionalOnClass(com.fasterxml.jackson.module.kotlin.KotlinModule.class)` and not `@ConditionalOnClass(Continuation::class)` in `SpringDocKotlinConfiguration`. By doing this, this autoconfiguration will only be triggered when the `jackson-module-kotlin` dependency is present, preventing any ClassNotFound issues.
> 
> I would add this information to #2114, but it's locked :)

@wleese, 

Comments unlocked for https://github.com/springdoc/springdoc-openapi/issues/2114!

**Comment by breun** [comment]
A project may have `kotlin-stdlib` on its class path, just because one of its dependencies uses Kotlin, without the project itself having any intention of using it. Currently in this case `SpringDocKotlinConfiguration` will be activated, because Kotlin's `Continuation` standard library class is present, but the construction will fail, because `KotlinModule.Builder` isn't on the classpath. I think that using `@ConditionalOnClass(KotlinModule.class)` would yield the expected result in this case.

**Comment by bnasslahsen** [comment]
@breun,

i invite you to follow https://github.com/springdoc/springdoc-openapi/issues/2114.
We will do something for it.

**Comment by bnasslahsen** [comment]
duplicate deletion
