### ISSUE TITLE
response status is 500 /v3/api-docs

### ISSUE THREAD

**Issue by brsun** [springdoc/springdoc-openapi#2485]
When I add validation annotations to a parameter, the documentation page shows a 500 error. However, when I remove the validation annotations, everything works fine.

with validation:
```
    @GetMapping("/test/{id}")
    public String testPost(@PathVariable @NotNull @Max(value = 100) Integer id) {
        return "Hello World!" + id;
    }
```
shows 500:
![image](https://github.com/springdoc/springdoc-openapi/assets/6804882/bcae5bc8-3b26-4946-857a-f144cf2ad0d5)

without validation:
```
    @GetMapping("/test/{id}")
    public String testPost(@PathVariable @NotNull Integer id) {
        return "Hello World!" + id;
    }
```
works well:
![image](https://github.com/springdoc/springdoc-openapi/assets/6804882/ea73c2bb-aa56-4f6a-bf73-eaeac9e35384)

versions:
     <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.1</version>
        <relativePath/>
    </parent>
    
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>2.3.0</version>
        </dependency>

        <dependency>
            <groupId>javax.validation</groupId>
            <artifactId>validation-api</artifactId>
            <version>2.0.1.Final</version>
        </dependency>

**Comment by bnasslahsen** [comment]
@brsun,

Not reproducible:
```yaml
openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /test/{id}:
    get:
      tags:
        - hello-controller
      operationId: testPost
      parameters:
        - name: id
          in: path
          required: true
          schema:
            maximum: 100
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
components: {}
```


Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed, but can be reopened if your provide the reproducible sample.

**Comment by ACACIANh** [comment]
I also experienced this when upgrading from Spring Boot 3.3.x to 3.4.x
The error message is as follows:
`jakarta.servlet.ServletException: Handler dispatch failed: java.lang.NoSuchMethodError: 'void org.springframework.web.method.ControllerAdviceBean.<init>(java.lang.Object)'`

**Comment by ACACIANh** [comment]
I solved this problem by upgrading the version of `springdoc-openapi-starter-webmvc-ui` from **2.0.2** to **2.7.0**.

https://github.com/springdoc/springdoc-openapi/issues/2813
https://github.com/springdoc/springdoc-openapi/releases/tag/v2.7.0

**Comment by Saedddd** [comment]
I also had this problem. It helped me that I changed the version from 2.4.2 to 2.7.0.

	<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
			<version>2.7.0</version>
		</dependency>

**Comment by Maarzano** [comment]
> I also had this problem. It helped me that I changed the version from 2.4.2 to 2.7.0.
> 
> ```
> <dependency>
> 		<groupId>org.springdoc</groupId>
> 		<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
> 		<version>2.7.0</version>
> 	</dependency>
> ```

I FUCKING LOVE YOU @Saedddd, i was trying, to access swagger to document my API and send requests more easily and quickly, it took me the whole week, but with a comment you helped me, may you be rewarded

**Comment by zzjcool** [comment]
> I solved this problem by upgrading the version of `springdoc-openapi-starter-webmvc-ui` from **2.0.2** to **2.7.0**.
> 
> [#2813](https://github.com/springdoc/springdoc-openapi/issues/2813) https://github.com/springdoc/springdoc-openapi/releases/tag/v2.7.0

This works for me!

**Comment by isra-rar** [comment]
> I solved this problem by upgrading the version of `springdoc-openapi-starter-webmvc-ui` from **2.0.2** to **2.7.0**.
> 
> [#2813](https://github.com/springdoc/springdoc-openapi/issues/2813) https://github.com/springdoc/springdoc-openapi/releases/tag/v2.7.0

IT FINALLY WORKED, THANK YOU
